import "@/styles/globals.css";

import { type Metadata } from "next";
import { Fira_Mono } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { NavBar } from "@/components/nav-bar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const font = Fira_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${font.className}`}>
      <body>
        <TRPCReactProvider>
          <div className="flex min-h-dvh bg-gradient-to-b from-[var(--ctp-base)] to-[var(--ctp-lavender)]">
            <NavBar />
            <main className="flex w-full flex-col items-center justify-center pb-16 md:pb-0 md:pl-16">
              <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
                {children}
              </div>
            </main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
